(tests
 (names t_common t_object_meta t_functor t_functor_views t_marshal_props
   t_api_method t_state_machine t_message t_cluster t_api_server
   t_reconcile_driver t_vreplica_set t_vreplica_set_reconciler
   t_vreplica_set_driver t_p4_roundtrip t_p4_oracle t_p4_invariants
   t_p4_enumerator t_p5_model_check t_p5_state_eq t_p5_cluster_check
   t_p5_mutation t_p6_step_view t_p6_discharge t_p6_vrs_liveness
   t_p6_mutation t_p7_concurrency t_p7_exec_api_server t_p7_correspondence
   t_p7_controller_runtime t_p7_mutation t_p8_settle t_p8_mutation
   t_v_deployment t_v_deployment_reconciler t_p9_two_controller t_p9_mutation
   t_v_stateful_set t_v_stateful_set_reconciler t_p10_witness t_p10_mutation
   t_p11_vsts_invariants t_p11_vsts_esr t_p11_vsts_liveness t_p11_mutation)
 (libraries anvil_support anvil_k8s_objects anvil_state_machine anvil_reconciler
   anvil_cluster anvil_controllers anvil_assurance anvil_checker anvil_proof
   anvil_exec comp_cat alcotest qcheck-core qcheck-alcotest)
 (flags
  (:standard -w +a-4-9-40-41-42-44-45-70 -open Anvil_support
   -open Anvil_k8s_objects -open Anvil_reconciler -open Anvil_state_machine
   -open Anvil_cluster -open Anvil_controllers)))
